{
 "title": "http-server-projeto-korp",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilidade do Serviço (UP/DOWN)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"http-server-projeto-korp\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Volume de Requisições por segundo",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{ method }} {{ path }}" }
   ]
  },
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total" }
   ]
  }
 ]
}